repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: python
    hooks:
      - id: clang-format
      - id: clang-tidy
        args:
          - "-p=build/"
          - "-checks=clang-analyzer-*,concurrency-*,modernize-*,performance-*,readability-*,llvm-*"
          - "-fix"
          - "--header-filter=.*"
          - "--warnings-as-errors=*"
