#ifndef SAKURA_CONSTANTS_HPP
#define SAKURA_CONSTANTS_HPP

constexpr unsigned int COLOR_TABLE_RAM_NUMBER_OF_COLORS_PER_AREA = 16;
constexpr unsigned int COLOR_TABLE_RAM_NUMBER_OF_AREAS = 16;
constexpr unsigned int COLOR_TABLE_RAM_NUMBER_OF_SECTIONS = 2;
constexpr unsigned int COLOR_TABLE_RAM_NUMBER_OF_COLORS_PER_SECTION =
    COLOR_TABLE_RAM_NUMBER_OF_COLORS_PER_AREA * COLOR_TABLE_RAM_NUMBER_OF_AREAS;
constexpr unsigned int COLOR_TABLE_RAM_NUMBER_OF_COLORS =
    COLOR_TABLE_RAM_NUMBER_OF_COLORS_PER_SECTION *
    COLOR_TABLE_RAM_NUMBER_OF_SECTIONS;
constexpr unsigned int COLOR_TABLE_RAM_DATA_LENGTH =
    COLOR_TABLE_RAM_NUMBER_OF_COLORS * 3;

#endif
