on: [push]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: UnsafePointer/cmake-clang-ninja-build-github-action@v1.1
        with:
          dir: "src"
